### PR TITLE
React integration

### PR DESCRIPTION
**Pull request by DhivinX**
xeokit-bim-viewer integration in React. 
However, please review whether the integration is correct.

### CODE REVIEW

**Comment by xeolabs** [comment]
A missing module perhaps?

````
lindsay@mousebear:~/xeolabs/xeokit-integration-examples$ pnpm install
Scope: all 7 workspace projects
Lockfile is up to date, resolution step is skipped

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.15.4 → 8.15.6.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.15.6   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Packages: +849 -9
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
Downloading registry.npmjs.org/typescript/4.9.5: 11.62 MB/11.62 MB, done
Progress: resolved 849, reused 281, downloaded 568, added 832, done
node_modules/.pnpm/core-js@3.36.1/node_modules/core-js: Running postinstall script, done in 62ms
apps/nuxt postinstall$ nuxt prepare
│  ERROR  Cannot find module 'bindings'
│ Require stack:
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/node-file-trace.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/index.js
│   Require stack:
│   - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js
│   - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/node-file-trace.js
│   - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/index.js
│   at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
│   at Module._load (node:internal/modules/cjs/loader:984:27)
│   at Module.require (node:internal/modules/cjs/loader:1231:19)
│   at require (node:internal/modules/helpers:179:18)
│   at Object.<anonymous> (/home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js:11:36)
│   at Module._compile (node:internal/modules/cjs/loader:1369:14)
│   at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
│   at Module.load (node:internal/modules/cjs/loader:1206:32)
│   at Module._load (node:internal/modules/cjs/loader:1022:12)
│   at Module.require (node:internal/modules/cjs/loader:1231:19) 
│  ERROR  Cannot find module 'bindings'
│ Require stack:
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/node-file-trace.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/index.js
└─ Failed in 5.7s at /home/lindsay/xeolabs/xeokit-integration-examples/apps/nuxt
 ELIFECYCLE  Command failed with exit code 1.
lindsay@mousebear:~/xeolabs/xeokit-integration-examples$ pnpm install
Scope: all 7 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
apps/nuxt postinstall$ nuxt prepare
│  ERROR  Cannot find module 'bindings'
│ Require stack:
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/node-file-trace.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/index.js
│   Require stack:
│   - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js
│   - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/node-file-trace.js
│   - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/index.js
│   at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
│   at Module._load (node:internal/modules/cjs/loader:984:27)
│   at Module.require (node:internal/modules/cjs/loader:1231:19)
│   at require (node:internal/modules/helpers:179:18)
│   at Object.<anonymous> (/home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js:11:36)
│   at Module._compile (node:internal/modules/cjs/loader:1369:14)
│   at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
│   at Module.load (node:internal/modules/cjs/loader:1206:32)
│   at Module._load (node:internal/modules/cjs/loader:1022:12)
│   at Module.require (node:internal/modules/cjs/loader:1231:19) 
│  ERROR  Cannot find module 'bindings'
│ Require stack:
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/analyze.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/node-file-trace.js
│ - /home/lindsay/xeolabs/xeokit-integration-examples/node_modules/.pnpm/@vercel+nft@0.26.4/node_modules/@vercel/nft/out/index.js
└─ Failed in 759ms at /home/lindsay/xeolabs/xeokit-integration-examples/apps/nuxt
 ELIFECYCLE  Command failed with exit code 1.
lindsay@mousebear:~/xeolabs/xeokit-integration-examples$ 

````

**Comment by DhivinX** [comment]
Which version of node js are you using?

**Comment by xeolabs** [comment]
v20.12.0

**Comment by DhivinX** [comment]
Remove `pnpm-lock.yaml` and all node_modules: 

```bash
rm pnpm-lock.yaml
rm -r node_modules
rm -r **/node_modules
```

And try again:

```bash
pnpm i
```

If works, then commit `pnpm-lock.yaml` again to the repo.

I'm on Linux Mint 21.3, and tested it on this system and Windows 11.
Which system do you using?

**Comment by xeolabs** [comment]
Works now, thanks
Ubuntu Ubuntu 22.04.4 LTS

**Pull request merged**
